project:
  type: website
lang: es
execute:
  freeze: auto  # re-render only when source changes
  echo: false

website:
  title: "Proyecto Tweets"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: "Home"
      - text: "Menu"
        menu:
          - "1. limpiando_data.qmd"
          - "2. exploracion.qmd"
          - "3. tipo_hashtags.qmd"

format:
  html:
    theme: flatly
    toc: true
