project:
  type: website
lang: es
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Proyecto Tweets"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: "Home"
      - text: "Menu"
        menu:
          - 1_limpiando_data.qmd
          - 2_exploracion.qmd

format:
  html:
    theme: flatly
    toc: true
