---
title: "notas_2_exploracion"
---

## Problema

-   Utilizar las métricas que sacó Daniel
    -   Relacionarlo a las tablas que se pusieron en el ppt del congreso.

-   Se necesita explorar las técnicas de análisis de redes para encontrar relaciones en la data de Twitter.
    -   Grafos

    -   Métricas

        -   **Betweenness Centrality** (28), es un indicador de la centralidad de la red. Es igual al número de caminos más cortos de todos los vértices a todos los otros que pasan a través de ese nodo. Un nodo con alto betweenness centrality tiene una *gran influencia* en la transferencia de los nodos a través de la red, asumiendo que cada nodo transfiere siguiendo los caminos más cortos

        -   **Closeness Centrality** (2), centralidad de intermediación, Son nodos que a pesar de tener pocas conexiones, sus arcos permiten llegar a todos los puntos de la red más rápidamente que desde cualquier otro punto. *Representan una excelente posición para monitorear el flujo de información de toda la red.*

        -   **Coeficiente de Clustering** (29), es el coeficiente de agrupamiento de un vértice en un grafo cuantifica qué tanto está de agrupado( o  interconectado) con sus vecinos. Se puede decir que si el vértice está agrupado como un clique (grafo completo) su valor es máximo, mientras que un valor pequeño indica un vértice poco agrupado en la red. También se le puede denominar como transitividad

        -   **Degree** (7), Es el grado de un vértice v es el número de líneas que tienen a v como nodo de uno de sus extremos

        -   **Distancia**, indica entre dos actores cómo de cerca uno está de otro

        -   **Eigenvector centrality**, \"*centralidad del vector\",* Es una medida de la influencia de un nodo en una red. Asigna puntuaciones relativas a todos los nodos de la red basada en el concepto de que las conexiones a los nodos de alta puntuación contribuyen más a la puntuación del nodo en cuestión de la igualdad de las conexiones a los nodos de baja puntuación

        -   **Densidad del grafo** (5.2), es el número total de relaciones existentes dividido por el total posible de la red (en densidad).

        -   **PageRank** (31), asigna de forma numérica la relevancia de los documentos indexados por un motor de búsqueda.

        -   **WordPair**, pares de palabras com osi fueran Vertex 1 y Vertex 2, y a partir de ello un Count. Necesario para realizar una red semántica (de palabras).
